### PR TITLE
fix: handle peer:disconnect event from connection manager

### PR DESCRIPTION
**Pull request by tuyennhv**
**Motivation**
Sometimes `onPeerDisconnected()` is not called by the registrar and it leaves a lot of open streams even through the peer is disconnected

**Description**
Handle `peer:disconnect` from connection manager

part of #313

### CODE REVIEW

**Comment by tuyennhv** [comment]
this should fix the issue that we keep pushing data to a closed raw stream
Screen Shot 2022-08-09 at 12 45 00

and it keeps accumulating inside the internal buffers of `pushable`

Screen Shot 2022-08-09 at 12 47 16

**Comment by wemeetagain** [comment]
LGTM @achingbrain do you have any comments on this before we merge?

**Comment by achingbrain** [comment]
Do you know under what circumstances onPeerDisconnected is not being called?

**Comment by wemeetagain** [comment]
Take a look at this issue https://github.com/ChainSafe/js-libp2p-gossipsub/issues/313

Not entirely sure what is triggering it in practice, but just looking at the code, it can happen when an inbound gossip stream is established with a peer that doesn't support (or doesn't successfully complete) the identify protocol. Then that peer disconnects.

**Comment by wemeetagain** [comment]
Discussed with @achingbrain , he will add more functionality upstream in js-libp2p to support this rather than make a change here.
When inbound or outbound protocol streams are negotiated, libp2p will make sure the protocol is registered to that peer in the protobook.

**Comment by wemeetagain** [comment]
closing in favor of https://github.com/libp2p/js-libp2p/pull/1341

**Pull request closed without merging**
